import type { Issue } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const mockIssues: Issue[] = [
  {
    id: 'mock-1',
    userId: 'user-1',
    title: 'Massive Pothole on Elm Street',
    description: 'A very large and dangerous pothole has formed in the middle of Elm Street, causing cars to swerve dangerously. It needs immediate attention before an accident occurs.',
    location: 'Elm Street, near the old theatre',
    reporterName: 'Jane Doe',
    reporterAvatarUrl: findImage('user-avatar-1')?.imageUrl,
    status: 'Reported',
    category: 'Pothole',
    severity: 'high',
    upvotes: 15,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-pothole')?.imageUrl,
    imageHint: findImage('issue-pothole')?.imageHint,
  },
  {
    id: 'mock-2',
    userId: 'user-2',
    title: 'Overflowing Bins at City Park',
    description: 'The garbage bins at City Park have not been emptied for over a week. They are overflowing and attracting pests. The smell is becoming unbearable for park visitors.',
    location: 'City Park, main entrance',
    reporterName: 'John Smith',
    reporterAvatarUrl: findImage('user-avatar-2')?.imageUrl,
    status: 'In Progress',
    category: 'Garbage',
    severity: 'medium',
    upvotes: 8,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-garbage')?.imageUrl,
    imageHint: findImage('issue-garbage')?.imageHint,
  },
  {
    id: 'mock-3',
    userId: 'user-3',
    title: 'Streetlight Out on Oak Avenue',
    description: 'The streetlight at the corner of Oak Avenue and 5th Street is completely out. It has been fixed and is now working correctly.',
    location: 'Corner of Oak Ave & 5th St',
    reporterName: 'Emily White',
    reporterAvatarUrl: findImage('user-avatar-3')?.imageUrl,
    status: 'Resolved',
    category: 'Street Light',
    severity: 'low',
    upvotes: 25,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-light')?.imageUrl,
    imageHint: findImage('issue-light')?.imageHint,
  },
  {
    id: 'mock-4',
    userId: 'user-4',
    title: 'Broken Swing at Willow Creek Playground',
    description: 'One of the swings at the playground has a broken chain, making it unsafe for children to use. It needs to be repaired or removed.',
    location: 'Willow Creek Playground',
    reporterName: 'Michael Brown',
    reporterAvatarUrl: findImage('user-avatar-4')?.imageUrl,
    status: 'Reported',
    category: 'Safety',
    severity: 'medium',
    upvotes: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-park')?.imageUrl,
    imageHint: findImage('issue-park')?.imageHint,
  },
  {
    id: 'mock-5',
    userId: 'user-1',
    title: 'Water Main Leak on Main Street',
    description: 'There is a significant water leak from a water main on Main Street. Water is pooling on the road and causing a hazard. A crew is on-site now.',
    location: '123 Main Street',
    reporterName: 'Jane Doe',
    reporterAvatarUrl: findImage('user-avatar-1')?.imageUrl,
    status: 'In Progress',
    category: 'Water',
    severity: 'high',
    upvotes: 42,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: findImage('issue-water-leak')?.imageUrl,
    imageHint: findImage('issue-water-leak')?.imageHint,
  },
  {
    id: 'mock-6',
    userId: 'user-2',
    title: 'Traffic Signal Malfunction at Grand Intersection',
    description: 'The traffic lights at the intersection of Grand and Central are stuck on red, causing major traffic jams. This has been resolved by the traffic department.',
    location: 'Grand & Central Ave',
    reporterName: 'John Smith',
    reporterAvatarUrl: findImage('user-avatar-2')?.imageUrl,
    status: 'Resolved',
    category: 'Traffic',
    severity: 'high',
    upvotes: 31,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-traffic-light')?.imageUrl,
    imageHint: findImage('issue-traffic-light')?.imageHint,
  },
  {
    id: 'mock-7',
    userId: 'user-3',
    title: 'Illegal Dumping on Industrial Rd',
    description: 'Someone has illegally dumped a large amount of construction debris on the side of Industrial Road. It needs to be cleaned up.',
    location: 'Industrial Road, past the warehouse',
    reporterName: 'Emily White',
    reporterAvatarUrl: findImage('user-avatar-3')?.imageUrl,
    status: 'Reported',
    category: 'Garbage',
    severity: 'medium',
    upvotes: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: findImage('issue-illegal-dumping')?.imageUrl,
    imageHint: findImage('issue-illegal-dumping')?.imageHint,
  },
  {
    id: 'mock-8',
    userId: 'user-4',
    title: 'Cracked Pavement on Bike Path',
    description: 'The pavement on the riverfront bike path is severely cracked and uneven. A temporary fix has been applied while waiting for full repaving.',
    location: 'Riverfront Bike Path, Mile 2',
    reporterName: 'Michael Brown',
    reporterAvatarUrl: findImage('user-avatar-4')?.imageUrl,
    status: 'In Progress',
    category: 'Pothole',
    severity: 'low',
    upvotes: 11,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-bike-path')?.imageUrl,
    imageHint: findImage('issue-bike-path')?.imageHint,
  },
  {
    id: 'mock-9',
    userId: 'user-1',
    title: 'Fallen Tree Branch Blocking Sidewalk',
    description: 'A large tree branch has fallen and is completely blocking the sidewalk on Maple Lane. The branch has been removed and the sidewalk is clear.',
    location: '45 Maple Lane',
    reporterName: 'Jane Doe',
    reporterAvatarUrl: findImage('user-avatar-1')?.imageUrl,
    status: 'Resolved',
    category: 'Other',
    severity: 'medium',
    upvotes: 18,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: findImage('issue-fallen-tree')?.imageUrl,
    imageHint: findImage('issue-fallen-tree')?.imageHint,
  },
];
